### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by JJK96** [71/dance#1]
I try to build the plugin with 

```
vsce package
```

```
Executing prepublish script 'npm run vscode:prepublish'...
 ERROR  Command failed: npm run vscode:prepublish
warning dance@0.1.0: The engine "vscode" appears to be invalid.
/bin/sh: ts-node: command not found
error Command failed with exit code 127.
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! dance@0.1.0 vscode:prepublish: `yarn run generate && yarn run compile`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the dance@0.1.0 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jjk/.npm/_logs/2019-06-17T12_21_36_192Z-debug.log
```

Any ideas on what might be the problem?

**Comment by 71** [comment]
It looks like the `ts-node` command cannot be found, even though it is listed in the `package.json` `devDependencies`. Did you install them (`npm install` or `yarn install`)?

**Comment by JJK96** [comment]
I didn't in that log output, this is the output where I did run `npm install` before.

```
Executing prepublish script 'npm run vscode:prepublish'...
 ERROR  Command failed: npm run vscode:prepublish
warning dance@0.1.0: The engine "vscode" appears to be invalid.
warning dance@0.1.0: The engine "vscode" appears to be invalid.
error Command failed with exit code 2.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! dance@0.1.0 vscode:prepublish: `yarn run generate && yarn run compile`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the dance@0.1.0 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jjk/.npm/_logs/2019-06-18T06_46_59_298Z-debug.log
```

And this is the debug log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'vscode:prepublish' ]
2 info using npm@6.9.0
3 info using node@v11.15.0
4 verbose run-script [ 'prevscode:prepublish',
4 verbose run-script   'vscode:prepublish',
4 verbose run-script   'postvscode:prepublish' ]
5 info lifecycle dance@0.1.0~prevscode:prepublish: dance@0.1.0
6 info lifecycle dance@0.1.0~vscode:prepublish: dance@0.1.0
7 verbose lifecycle dance@0.1.0~vscode:prepublish: unsafe-perm in lifecycle true
8 verbose lifecycle dance@0.1.0~vscode:prepublish: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/jjk/git/dance/node_modules/.bin:/home/jjk/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/jjk/bin:/home/jjk/.local/bin:/home/jjk/bin/perl:/home/jjk/.config/composer/vendor/bin:/home/jjk/.yarn/bin:/home/jjk/.gem/ruby/2.5.0/bin:/home/jjk/go/bin:/home/jjk/.cargo/bin:/home/jjk/.config/kak/bin:/home/jjk/perl5/bin:/home/jjk/bin:/home/jjk/.local/bin:/home/jjk/bin/perl:/home/jjk/.config/composer/vendor/bin:/home/jjk/.yarn/bin:/home/jjk/.gem/ruby/2.5.0/bin:/home/jjk/go/bin:/home/jjk/.cargo/bin:/home/jjk/.config/kak/bin:/home/jjk/perl5/bin:/home/jjk/bin:/home/jjk/bin/perl:/home/jjk/.config/composer/vendor/bin:/home/jjk/.yarn/bin:/home/jjk/.gem/ruby/2.5.0/bin:/home/jjk/go/bin:/home/jjk/.cargo/bin:/home/jjk/.config/kak/bin:/home/jjk/perl5/bin
9 verbose lifecycle dance@0.1.0~vscode:prepublish: CWD: /home/jjk/git/dance
10 silly lifecycle dance@0.1.0~vscode:prepublish: Args: [ '-c', 'yarn run generate && yarn run compile' ]
11 silly lifecycle dance@0.1.0~vscode:prepublish: Returned: code: 2  signal: null
12 info lifecycle dance@0.1.0~vscode:prepublish: Failed to exec vscode:prepublish script
13 verbose stack Error: dance@0.1.0 vscode:prepublish: `yarn run generate && yarn run compile`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:193:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:193:13)
13 verbose stack     at maybeClose (internal/child_process.js:999:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
14 verbose pkgid dance@0.1.0
15 verbose cwd /home/jjk/git/dance
16 verbose Linux 5.1.9-arch1-1-ARCH
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "vscode:prepublish"
18 verbose node v11.15.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 2
22 error dance@0.1.0 vscode:prepublish: `yarn run generate && yarn run compile`
22 error Exit status 2
23 error Failed at the dance@0.1.0 vscode:prepublish script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by 71** [comment]
Noted. I tried repro'ing on Linux, by I'm having another issue, and don't really have time to look into it. I did look up your error, and it [might come from a problem in the current environment](https://stackoverflow.com/questions/42308879)?

**Comment by JJK96** [comment]
Thanks for looking into it
I followed the top answer in clearing the npm cache and removing `node_modules` but no succes

**Comment by JJK96** [comment]
The error happens in `yarn run compile`:

```
yarn run v1.16.0
$ tsc -p ./
src/commands/index.ts(103,9): error TS2322: Type 'RegExp | undefined' is not assignable to type 'InputTypeMap[Input]'.
  Type 'undefined' is not assignable to type 'InputTypeMap[Input]'.
    Type 'undefined' is not assignable to type 'void & RegExp & number & number[] & string'.
      Type 'undefined' is not assignable to type 'RegExp'.
src/commands/index.ts(106,9): error TS2322: Type 'number | undefined' is not assignable to type 'InputTypeMap[Input]'.
  Type 'undefined' is not assignable to type 'InputTypeMap[Input]'.
src/commands/index.ts(109,9): error TS2322: Type 'number[] | undefined' is not assignable to type 'InputTypeMap[Input]'.
  Type 'undefined' is not assignable to type 'InputTypeMap[Input]'.
src/commands/index.ts(112,9): error TS2322: Type 'string | undefined' is not assignable to type 'InputTypeMap[Input]'.
  Type 'undefined' is not assignable to type 'InputTypeMap[Input]'.
src/commands/index.ts(115,9): error TS2322: Type 'string' is not assignable to type 'InputTypeMap[Input]'.
  Type 'string' is not assignable to type 'void & RegExp & number & number[] & string'.
    Type 'string' is not assignable to type 'void'.
src/commands/index.ts(119,42): error TS2454: Variable 'input' is used before being assigned.
src/commands/index.ts(122,93): error TS2454: Variable 'input' is used before being assigned.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by 71** [comment]
Regarding that last error you mentioned, I have it fixed on a local build but haven't had the time to push it yet. Sorry for the delay!

**Comment by 71** [comment]
c36b86a0092d3a9aea300de7a56708a8b9ac9d17 fixed this!

**Comment by JJK96** [comment]
Correct, I can compile fine now

**Comment by JJK96** [comment]
Sorry if this is an error on my machine, but:

`yarn run compile`

```
yarn run v1.19.1
warning dance@0.1.1: The engine "vscode" appears to be invalid.
$ tsc -p ./
src/commands/goto.ts:24:10 - error TS7030: Not all code paths return a value.

24 function executeGoto(gotoType: number, editor: vscode.TextEditor, count: number, extend: boolean) {
            ~~~~~~~~~~~

src/commands/move.ts:8:148 - error TS2304: Cannot find name 'Selection'.

8 function registerMovement(cmd: Command, modifier: (selection: vscode.Selection, editor: vscode.TextEditor, state: CommandState<InputKind.None>) => Selection) {
                                                                                                                                                     ~~~~~~~~~

../../node_modules/@types/bs58/index.d.ts:7:10 - error TS2305: Module '"../../base-x/src"' has no exported member 'BaseConverter'.

7 import { BaseConverter } from 'base-x';
           ~~~~~~~~~~~~~

../../node_modules/@types/bs58/index.d.ts:7:31 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

7 import { BaseConverter } from 'base-x';
                                ~~~~~~~~


Found 4 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Maybe you should push your `package-lock.json` so that others have the correct versions of packages. I assume that the problem is related to that.

**Comment by 71** [comment]
Thanks for the report. 0d7014fa0f5748dd4419be6f042741aff06c276a and 15099c3097a1024eb6b303a760741128d5f386a4 should fix this.
