### ISSUE TITLE
Switching to a non-editor tab breaks registers view

### ISSUE THREAD

**Issue by mjpieters** [71/dance#316]
Type: <b>Bug</b>

If I open a non-editor view (like the settings page), and error message ("active editor is required") is shown and the Dance registers view is wiped empty. Only a "Developer: Reload window" command brings it back.

I see this both with version 0.5.11 (release) and 0.5.12004 (pre-release).

To reproduce:

- Open a file editor
- Execute the "Dance: Focus on Registers View" command; it shows a tree of registers and their contents
- Open preferences (command "Preferences: Open User Settings")
- The error message "active editor is required" pops up. The Dance registers view now only shows the 'Global' top-level entry, and is otherwise empty. For a remote session, there is a 'exthost' entry as well.
- Switch back to the file editor, observe that the tree remains empty, apart from the 'Global' top-level entry and the document-specific entry.

The extension host output has this traceback:

```
2023-10-30 13:14:43.638 [error] Error: active editor required
	at EditorRequiredError.throwUnlessAvailable (/Users/USERNAME/.vscode/extensions/gregoire.dance-0.5.12004/out/extension.js:1:2472)
	at activeEditor (/Users/USERNAME/.vscode/extensions/gregoire.dance-0.5.12004/out/extension.js:19:52674)
	at Oo.getter (/Users/USERNAME/.vscode/extensions/gregoire.dance-0.5.12004/out/extension.js:21:1662)
	at Oo.get (/Users/USERNAME/.vscode/extensions/gregoire.dance-0.5.12004/out/extension.js:19:55867)
	at Go.values (/Users/USERNAME/.vscode/extensions/gregoire.dance-0.5.12004/out/extension.js:29:52170)
	at Go.shouldShow (/Users/USERNAME/.vscode/extensions/gregoire.dance-0.5.12004/out/extension.js:29:52043)
	at /Users/USERNAME/.vscode/extensions/gregoire.dance-0.5.12004/out/extension.js:29:49909
	at Array.map (<anonymous>)
	at zo.getChildren (/Users/USERNAME/.vscode/extensions/gregoire.dance-0.5.12004/out/extension.js:29:49888)
	at c.Y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:16342)
	at c.getChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:12710)
	at a.$getChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:9273)
	at i.S (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:10827)
	at i.Q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:10593)
	at i.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:9683)
	at i.L (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:8762)
	at s.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:7565)
	at c.z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at m.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:14010)
	at s.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:7902)
	at c.z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at m.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:14010)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:6182)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
```

Extension version: 0.5.12004
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:57:32.750Z)
OS version: Darwin arm64 21.6.0
Modes:
Remote OS version: Linux x64 5.10.0-0.deb10.16-amd64

**Comment by 71** [comment]
Hello, and thank you for the bug report! My debugger is behaving weirdly so it wasn't trivial to fix, but I finally got it!
