### ISSUE TITLE
registers view "Cannot read properties of undefined (reading 'iconName')"

### ISSUE THREAD

**Issue by mjpieters** [71/dance#317]
Type: <b>Bug</b>

When you open the dance registers view, an errror message pops up: *Cannot read properties of undefined (reading 'iconName')*. I can see this message both on the release version (0.5.11) and on the pre-release version (0.5.12004) of the extension.

To reproduce, open an editor, then execute the 'Dance: Focus on Registers View' command.

The error message is not logged in any of the logs in the 'output' tab of VSCode, but when you toggle the developer tools the console there does provide a traceback:

```
TypeError: Cannot read properties of undefined (reading 'iconName')
    at /Users/USERNAME/.vscode/extensions/gregoire.dance-0.5.12004/out/extension.js:29:49670
    at Array.filter (<anonymous>)
    at zo.getChildren (/Users/USERNAME/.vscode/extensions/gregoire.dance-0.5.12004/out/extension.js:29:49658)
    at c.Y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:16342)
    at c.getChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:12710)
    at a.$getChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:9273)
    at i.S (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:10827)
    at i.Q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:10593)
    at i.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:9683)
    at i.L (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:8762)
    at s.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:7565)
    at c.z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
    at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
    at m.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:14010)
    at s.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:7902)
    at c.z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
    at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
    at m.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:14010)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:6182)
    at MessagePortMain.emit (node:events:513:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
```

Extension version: 0.5.12004
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:57:32.750Z)
OS version: Darwin arm64 21.6.0
Modes:
Remote OS version: Linux x64 5.10.0-0.deb10.16-amd64

**Comment by 71** [comment]
Thanks for the report! Fixed along with #316 in 5fffe3be2bebd92c6c73959ef0c73c09aff7fee8.
